### ISSUE TITLE
Update privacy policy to meet current cancelation of Privacy Shield by CURIA

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [AppFridaysForFutureDE/static#23]
To avoid legal issues, you should update your privacy policy as Privacy Shield was recently canceled by [CURIA case no. C-311/18](http://curia.europa.eu/juris/document/document.jsf?text=&docid=228677&pageIndex=0&doclang=en&mode=lst&dir=&occ=first&part=1&cid=12159283). Pleas ask at Google Analytics for a more current text snippet or temporarily disable analytics until they provide a new one.

```quote
 Google Analytics

    Diese Website nutzt aufgrund unserer berechtigten Interessen zur
    Optimierung und Analyse unseres Online-Angebots im Sinne des Art. 6 Abs.
    1 lit. f. DSGVO den Dienst „Google Analytics“, welcher von der Google
    Inc. (1600 Amphitheatre Parkway Mountain View, CA 94043, USA) angeboten
    wird. Der Dienst (Google Analytics) verwendet „Cookies“ – Textdateien,
    welche auf Ihrem Endgerät gespeichert werden. Die durch die Cookies
    gesammelten Informationen werden im Regelfall an einen Google-Server in
    den USA gesandt und dort gespeichert.
    Google LLC hält das europäische Datenschutzrecht ein und ist unter dem
    Privacy-Shield-Abkommen zertifiziert:


  https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&status=Active
```

**Comment by redsolver** [comment]
Google Analytics isn't used on our website and apps, we will remove this snippet soon.

**Comment by redsolver** [comment]
Removed in https://github.com/AppFridaysForFutureDE/static/commit/c79492fa64a9b9bfc67a64c507fb8be8e2f62035
