### ISSUE TITLE
Link zu Source

### ISSUE THREAD

**Issue by waweic** [AppFridaysForFutureDE/static#3]
Moin, habe euch hier auf GitHub nur per Zufall gefunden, das wäre einfacher gewesen, wenn ihr auf eurer Seite nen Link hierher gehabt hättet. Ist das gewünscht? Das würde außerdem Vertrauen in die Software aufbauen, die ihr schreibt

**Comment by ferb300** [comment]
Hi, ja das ist tatsächlich so gewünscht. Unsere Software ist zwar aus Transparenzgründen zu 100% Open-Source, aber wir möchten vermeiden, von Trollen und Hackern leicht ausfindig gemacht zu werden und verlinken den Quellcode deshalb nur in unserem Impressum.
Danke für die Nachfrage :)
