### ISSUE TITLE
 Statische Html Seite auf dem Backend einrichten

### ISSUE THREAD

**Issue by ferb300** [AppFridaysForFutureDE/static#7]
Es soll eine Statische Html Seite auf dem Backendgeben die via Webview in die App einbezogen wird. Wichtig wäre, dass die Seite auch über https erreichbar ist.
Der Inhalt ist erstmal nicht so relevant
Und die Url eigentlich auch nicht. Vlt sowas wie strike-site oder so

[MOVED FROM backend]

**Comment by NikolaiKircher** [comment]
ich denke das ist erledigt, oder? @ferb300
